name: "AdeeActions"

on:
  push:
    branches: [ adeeBranch ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Extract:
    runs-on: ubuntu-latest

    steps:
      - name: API Call
        run: https://api.github.com/repos/Adee07/AdeeRepo/pulls?state=closed
    
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Mads Special Command
        run: echo AMADOOO
        
      - name: Create File mads
        run: touch mads
        
      - name: Run Multiple Commands
        run: |
          echo 1. What is in this directory?
          ls -lah
          echo
          echo 2. Is Java installed?
          java -version
          echo
          echo 3. Is Git Installed?
          git --version
          echo
          echo 4. What is the workspace location?
          echo $RUNNER_WORKSPACE
          echo
          echo 5. Who is running this script?
          whoami
          echo
          echo 6. How is the disc laid out?
          df
          echo
          echo 7. What environment variables are available?
          env
  

        
