name: "AdeeActions"

on:
  push:
    branches: [ adeeBranch ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Mads Special Command
        run: echo AMADOOO
        
      - name: Create File mads
        run: touch mads
